import {
  Client,
  Property,
  Opportunity,
  Practice,
  DocumentItem,
  Task,
  Deadline,
  Appointment,
  WaitingItem,
} from './types';

export const INITIAL_CLIENTS: Client[] = [
  {
    id: 'cli-1',
    firstName: 'Mario',
    lastName: 'Rossi',
    phone: '+39 340 1234567',
    email: 'm.rossi@email.it',
    type: 'seller',
    fiscalCode: 'RSSMRA80A01H501U',
    city: 'Terrasini',
    address: 'Via Roma 18',
    notes: 'Disponibile per sopralluoghi il martedì e giovedì pomeriggio.',
    createdAt: '2023-09-15',
  },
  {
    id: 'cli-2',
    firstName: 'Giuseppe',
    lastName: 'Marino',
    phone: '+39 340 9876543',
    email: 'g.marino@email.it',
    type: 'seller',
    fiscalCode: 'MRNGPP75M12G273K',
    city: 'Terrasini',
    address: 'Via Roma 12',
    notes: 'Molto motivato alla vendita per trasferimento lavorativo a Milano.',
    createdAt: '2023-10-01',
  },
  {
    id: 'cli-3',
    firstName: 'Laura',
    lastName: 'Bianchi',
    phone: '+39 338 5544332',
    email: 'l.bianchi@studiolegale.it',
    type: 'both',
    fiscalCode: 'BNCLRA85P45G273X',
    city: 'Palermo',
    address: 'Via Libertà 42',
    notes: 'Avvocato, segue la vendita dell immobile ereditato di famiglia.',
    createdAt: '2023-09-20',
  },
  {
    id: 'cli-4',
    firstName: 'Roberto',
    lastName: 'Ferrara',
    phone: '+39 320 8899776',
    email: 'r.ferrara@libero.it',
    type: 'seller',
    fiscalCode: 'FRRRBT68C14F205W',
    city: 'Monreale',
    address: 'Via Pietro Novelli 14',
    notes: 'Interessato a una stima prudenziale prima di firmare il mandato esclusivo.',
    createdAt: '2023-10-05',
  },
  {
    id: 'cli-5',
    firstName: 'Sofia',
    lastName: 'Russo',
    phone: '+39 347 1122334',
    email: 'sofia.russo@gmail.com',
    type: 'seller',
    fiscalCode: 'RSSSFO92T50C351Y',
    city: 'Cinisi',
    address: 'Via dei Mulini 7',
    notes: 'Immobile già libero, chiavi già consegnate all agenzia.',
    createdAt: '2023-10-10',
  },
  {
    id: 'cli-6',
    firstName: 'Antonio',
    lastName: 'Greco',
    phone: '+39 333 4455667',
    email: 'a.greco@virgilio.it',
    type: 'seller',
    fiscalCode: 'GRCNTN70E10H501Z',
    city: 'Palermo',
    address: 'Via Notarbartolo 88',
    notes: 'Proprietario di due locali commerciali a reddito.',
    createdAt: '2023-10-12',
  },
];

export const INITIAL_PROPERTIES: Property[] = [
  {
    id: 'prop-1',
    address: 'Via Roma 18',
    civicNumber: '18',
    municipality: 'Terrasini',
    province: 'PA',
    area: 'Centro Storico',
    type: 'Appartamento',
    approximateSurface: 115,
    rooms: 4,
    bathrooms: 2,
    floor: '2° con ascensore',
    estimatedValue: 285000,
    owners: ['cli-1'],
    energyClass: 'C',
    notes: 'Completamente ristrutturato nel 2021. Balcone vista mare.',
  },
  {
    id: 'prop-2',
    address: 'Via Roma 12',
    civicNumber: '12',
    municipality: 'Terrasini',
    province: 'PA',
    area: 'Zona Mare / Scogliera',
    type: 'Villa Singola',
    approximateSurface: 160,
    rooms: 6,
    bathrooms: 3,
    floor: 'Piano terra + primo',
    estimatedValue: 390000,
    owners: ['cli-2'],
    energyClass: 'D',
    notes: 'Giardino di 400 m² appena rifatto. Doppio ingresso carrabile.',
  },
  {
    id: 'prop-3',
    address: 'Via Libertà 42',
    civicNumber: '42',
    municipality: 'Palermo',
    province: 'PA',
    area: 'Politeama / Libertà',
    type: 'Appartamento',
    approximateSurface: 185,
    rooms: 6,
    bathrooms: 2,
    floor: '3° piano nobiliare',
    estimatedValue: 475000,
    owners: ['cli-3'],
    energyClass: 'F',
    notes: 'Palazzo d epoca con portineria. Soffitti affrescati originali.',
  },
  {
    id: 'prop-4',
    address: 'Via Pietro Novelli 14',
    civicNumber: '14',
    municipality: 'Monreale',
    province: 'PA',
    area: 'Panoramica',
    type: 'Villa Singola',
    approximateSurface: 220,
    rooms: 7,
    bathrooms: 3,
    floor: 'Su 2 livelli',
    estimatedValue: 340000,
    owners: ['cli-4'],
    energyClass: 'G',
    notes: 'Vista panoramica sul Golfo di Palermo. Necessita ammodernamento.',
  },
  {
    id: 'prop-5',
    address: 'Via dei Mulini 7',
    civicNumber: '7',
    municipality: 'Cinisi',
    province: 'PA',
    area: 'Centro',
    type: 'Appartamento',
    approximateSurface: 95,
    rooms: 3,
    bathrooms: 1,
    floor: '1° piano',
    estimatedValue: 165000,
    owners: ['cli-5'],
    energyClass: 'E',
    notes: 'Ideale per giovani coppie o investimento per locazione turistica.',
  },
];

export const INITIAL_OPPORTUNITIES: Opportunity[] = [
  {
    id: 'opp-1',
    clientId: 'cli-2',
    propertyId: 'prop-2',
    sellerIntent: 'Alto',
    readiness: 72,
    priority: 'HOT',
    sellingTimeframe: 'Entro 3 mesi',
    motivation: 'Trasferimento lavorativo fuori regione (Milano)',
    briefing:
      'Cliente molto motivato alla vendita per trasferimento lavorativo. Ha già fatto valutare l immobile da un altra agenzia ma non è soddisfatto della perizia. Insistere su tempistiche rapide e valorizzazione degli spazi esterni (giardino appena rifatto).',
    appointmentDate: 'Oggi, ore 17:00',
    declaredDocuments: [
      {
        id: 'ddoc-1',
        label: 'Atto di provenienza (dichiarato presente)',
        category: 'immobile',
        declaredPresent: true,
      },
      {
        id: 'ddoc-2',
        label: 'Planimetria Catastale aggiornata',
        category: 'immobile',
        declaredPresent: true,
      },
      {
        id: 'ddoc-3',
        label: 'Attestato Prestazione Energetica (da richiedere)',
        category: 'immobile',
        declaredPresent: false,
      },
      {
        id: 'ddoc-4',
        label: 'Documenti identità e codice fiscale proprietario',
        category: 'cliente',
        declaredPresent: true,
      },
    ],
    recommendedAction: 'Contattare oggi',
    nextAction: 'Incontro conoscitivo e presentazione piano di vendita',
    status: 'active',
    estimatedPrice: 390000,
    preparationAdvice: {
      sintesi:
        'Proprietario determinato. Vuole vendere entro l anno per ragioni professionali. Sensibile alla trasparenza sui costi di agenzia.',
      daApprofondire: [
        'Presenza di eventuali difformità edilizie post-ristrutturazione',
        'Stato mutuo residuo e tempi di svincolo ipoteca',
        'Accordo definitivo tra comproprietari',
      ],
      domandeConsigliate: [
        'Ha già una data prefissata per il trasferimento a Milano?',
        'È disponibile a valutare una proposta con caparra confirmatoria a breve?',
        'Ci sono arredi su misura inclusi nella trattativa?',
      ],
      prossimaAzione:
        'Confermare appuntamento delle 17:00 e preparare la cartella di presentazione comparativa.',
    },
  },
  {
    id: 'opp-2',
    clientId: 'cli-5',
    propertyId: 'prop-5',
    sellerIntent: 'Alto',
    readiness: 85,
    priority: 'HOT',
    sellingTimeframe: 'Immediato',
    motivation: 'Liquidazione quota ereditaria tra fratelli',
    briefing:
      'Immobile libero e subito visionabile. Tutti i documenti catastali sono già in possesso del notaio di famiglia.',
    appointmentDate: 'Domani, 10:30',
    declaredDocuments: [
      { id: 'ddoc-21', label: 'Atto di provenienza', category: 'immobile', declaredPresent: true },
      { id: 'ddoc-22', label: 'Planimetria catastale', category: 'immobile', declaredPresent: true },
      { id: 'ddoc-23', label: 'APE in corso di validità', category: 'immobile', declaredPresent: true },
    ],
    recommendedAction: 'Acquisire mandato esclusivo',
    nextAction: 'Firma incarico con provvigione standard',
    status: 'active',
    estimatedPrice: 165000,
    preparationAdvice: {
      sintesi: 'Pratica altamente snella, documentazione quasi completa.',
      daApprofondire: ['Delega firmata da tutti i comproprietari'],
      domandeConsigliate: ['Tutti i coeredi sono allineati sul prezzo minimo di realizzo?'],
      prossimaAzione: 'Inviare bozza del mandato per revisione preventiva.',
    },
  },
  {
    id: 'opp-3',
    clientId: 'cli-4',
    propertyId: 'prop-4',
    sellerIntent: 'Basso',
    readiness: 42,
    priority: 'COLD',
    sellingTimeframe: '6-12 mesi',
    motivation: 'Curiosità sul valore di mercato attuale',
    briefing:
      'Il proprietario vorrebbe vendere solo se ottiene una cifra sopra mercato. Nessuna fretta. Documentazione catastale da verificare per tettoia esterna.',
    declaredDocuments: [
      { id: 'ddoc-31', label: 'Atto di provenienza', category: 'immobile', declaredPresent: true },
      { id: 'ddoc-32', label: 'Planimetria catastale', category: 'immobile', declaredPresent: false },
    ],
    recommendedAction: 'Inviare report di stima informativo',
    nextAction: 'Follow-up telefonico tra 15 giorni',
    status: 'active',
    estimatedPrice: 340000,
  },
  {
    id: 'opp-4',
    clientId: 'cli-6',
    propertyId: 'prop-3',
    sellerIntent: 'Medio',
    readiness: 58,
    priority: 'WARM',
    sellingTimeframe: '3-6 mesi',
    motivation: 'Reinvestimento in immobile commerciale a reddito',
    briefing:
      'Cliente investitore seriale. Chiede massima discrezione e tempistiche precise per reinvestire la liquidità.',
    declaredDocuments: [
      { id: 'ddoc-41', label: 'Atto di provenienza', category: 'immobile', declaredPresent: true },
      { id: 'ddoc-42', label: 'Planimetria catastale', category: 'immobile', declaredPresent: true },
      { id: 'ddoc-43', label: 'APE', category: 'immobile', declaredPresent: false },
    ],
    recommendedAction: 'Fissare sopralluogo tecnico',
    nextAction: 'Richiesta accesso agli atti in comune',
    status: 'active',
    estimatedPrice: 475000,
  },
];

export const INITIAL_PRACTICES: Practice[] = [
  {
    id: 'prat-1',
    code: 'PRT-2023-089',
    clientId: 'cli-1',
    propertyId: 'prop-1',
    practiceType: 'Compravendita',
    status: 'In corso',
    mandateStatus: 'da_firmare',
    amlStatus: 'in_corso',
    documentStatus: 'in_corso',
    proposalStatus: 'nessuna',
    openedDate: '12 Ott 2023',
    assignedAgent: {
      name: 'Luca Bianchi',
      initials: 'LB',
    },
    estimatedValue: 285000,
    nextAction: {
      title: 'Carica la Planimetria Catastale',
      description:
        'Carica la Planimetria Catastale per permettere la generazione automatica dell Attestato di Prestazione Energetica (APE) e procedere con la firma dell incarico.',
      ctaText: 'Carica Planimetria',
      targetSection: 'documenti',
      documentIdToUpload: 'doc-2',
    },
    amlWorkflow: {
      clienteIdentificato: true,
      informazioniRaccolte: true,
      titolareEffettivoVerificato: false,
      fascicoloCompleto: false,
      notes: 'In attesa di verifica documento del comproprietario.',
    },
    notes: [
      {
        id: 'not-1',
        date: 'Oggi',
        time: '10:30',
        author: 'Luca Bianchi',
        text: 'Cliente ha confermato la disponibilità per il sopralluogo tecnico di domani.',
      },
      {
        id: 'not-2',
        date: 'Ieri',
        time: '16:45',
        author: 'Luca Bianchi',
        text: 'Manca ancora la planimetria aggiornata. Sollecitato il venditore via email.',
      },
    ],
    timeline: [
      { id: 'time-1', date: '10 Ott 2023', title: 'Acquisizione', completed: true },
      { id: 'time-2', date: '15 Ott 2023', title: 'Valutazione', completed: true },
      { id: 'time-3', date: 'Oggi', title: 'Incarico', completed: false, current: true },
      { id: 'time-4', date: 'In attesa', title: 'Pubblicazione annuncio', completed: false },
      { id: 'time-5', date: 'In attesa', title: 'Raccolta proposte', completed: false },
    ],
  },
  {
    id: 'prat-2',
    code: 'PRT-2023-094',
    clientId: 'cli-3',
    propertyId: 'prop-3',
    practiceType: 'Compravendita',
    status: 'In corso',
    mandateStatus: 'firmato',
    amlStatus: 'da_verificare',
    documentStatus: 'in_corso',
    proposalStatus: 'nessuna',
    openedDate: '18 Ott 2023',
    assignedAgent: {
      name: 'Anna Morante',
      initials: 'AM',
    },
    estimatedValue: 475000,
    nextAction: {
      title: 'Antiriciclaggio da continuare',
      description: 'Completa la verifica titolare effettivo per conformità fascicolo cliente.',
      ctaText: 'Continua verifica AML',
      targetSection: 'aml',
    },
    amlWorkflow: {
      clienteIdentificato: true,
      informazioniRaccolte: true,
      titolareEffettivoVerificato: false,
      fascicoloCompleto: false,
      notes: 'Acquisita visura camerale studio associato.',
    },
    notes: [
      {
        id: 'not-21',
        date: '20 Ott 2023',
        time: '11:15',
        author: 'Anna Morante',
        text: 'Incarico di vendita firmato digitalmente. Inizio raccolta documentazione urbanistica.',
      },
    ],
    timeline: [
      { id: 'time-21', date: '18 Ott 2023', title: 'Acquisizione', completed: true },
      { id: 'time-22', date: '20 Ott 2023', title: 'Incarico firmato', completed: true },
      { id: 'time-23', date: 'Oggi', title: 'Antiriciclaggio', completed: false, current: true },
    ],
  },
  {
    id: 'prat-3',
    code: 'PRT-2023-102',
    clientId: 'cli-6',
    propertyId: 'prop-4',
    practiceType: 'Compravendita',
    status: 'In attesa',
    mandateStatus: 'da_preparare',
    amlStatus: 'non_avviato',
    documentStatus: 'incompleto',
    proposalStatus: 'nessuna',
    openedDate: '22 Ott 2023',
    assignedAgent: {
      name: 'Luca Bianchi',
      initials: 'LB',
    },
    estimatedValue: 340000,
    nextAction: {
      title: 'Predisponi bozza incarico',
      description: 'Definisci la percentuale provvigionale concordata con il cliente.',
      ctaText: 'Prepara Incarico',
      targetSection: 'incarico',
    },
    amlWorkflow: {
      clienteIdentificato: false,
      informazioniRaccolte: false,
      titolareEffettivoVerificato: false,
      fascicoloCompleto: false,
    },
    notes: [],
    timeline: [{ id: 'time-31', date: '22 Ott 2023', title: 'Acquisizione', completed: true, current: true }],
  },
];

export const INITIAL_DOCUMENTS: DocumentItem[] = [
  // Documents for Practice PRT-2023-089 (Mario Rossi)
  {
    id: 'doc-1',
    practiceId: 'prat-1',
    category: 'immobile',
    label: 'APE',
    subtitle: 'Attestato Prestazione Energetica',
    status: 'Disponibile',
    mockFileName: 'APE_ViaRoma18_ClasseC.pdf',
    updatedAt: '14 Ott 2023',
    expiryDate: '2033-10-14',
    isMissingRequired: false,
  },
  {
    id: 'doc-2',
    practiceId: 'prat-1',
    category: 'immobile',
    label: 'Planimetria',
    subtitle: 'Catastale aggiornata',
    status: 'Da recuperare',
    isMissingRequired: true,
  },
  {
    id: 'doc-3',
    practiceId: 'prat-1',
    category: 'immobile',
    label: 'Atto di Provenienza',
    subtitle: 'Rogito precedente',
    status: 'Da recuperare',
    isMissingRequired: true,
  },
  {
    id: 'doc-4',
    practiceId: 'prat-1',
    category: 'antiriciclaggio',
    label: 'Modulo Adeguata Verifica',
    subtitle: 'Firmato digitalmente',
    status: 'In attesa',
    isMissingRequired: false,
  },
  {
    id: 'doc-5',
    practiceId: 'prat-1',
    category: 'cliente',
    label: 'Carta d identità',
    subtitle: 'Scad. 2028',
    status: 'Disponibile',
    mockFileName: 'CI_Rossi_Mario.pdf',
    updatedAt: '12 Ott 2023',
    expiryDate: '2028-05-20',
  },
  {
    id: 'doc-6',
    practiceId: 'prat-1',
    category: 'cliente',
    label: 'Codice Fiscale',
    subtitle: 'Verificato',
    status: 'Disponibile',
    mockFileName: 'CF_Rossi_Mario.pdf',
    updatedAt: '12 Ott 2023',
  },
  {
    id: 'doc-7',
    practiceId: 'prat-1',
    category: 'incarico',
    label: 'Mandato di Vendita',
    subtitle: 'Scad: 15 Mag 2024',
    status: 'Da verificare',
    isMissingRequired: true,
  },

  // Documents for Practice PRT-2023-094 (Laura Bianchi)
  {
    id: 'doc-21',
    practiceId: 'prat-2',
    category: 'immobile',
    label: 'Atto di Provenienza',
    subtitle: 'Dichiarazione di Successione',
    status: 'Disponibile',
    mockFileName: 'Successione_Bianchi.pdf',
    updatedAt: '19 Ott 2023',
  },
  {
    id: 'doc-22',
    practiceId: 'prat-2',
    category: 'cliente',
    label: 'Carta d identità',
    subtitle: 'Scad. 2029',
    status: 'Disponibile',
    mockFileName: 'CI_Laura_Bianchi.pdf',
    updatedAt: '18 Ott 2023',
  },
  {
    id: 'doc-23',
    practiceId: 'prat-2',
    category: 'antiriciclaggio',
    label: 'Dichiarazione Titolare Effettivo',
    subtitle: 'Da completare',
    status: 'Da recuperare',
    isMissingRequired: true,
  },
  {
    id: 'doc-24',
    practiceId: 'prat-2',
    category: 'incarico',
    label: 'Mandato di Vendita Esclusivo',
    subtitle: 'Firmato digitalmente',
    status: 'Disponibile',
    mockFileName: 'Mandato_Esclusivo_ViaLiberta.pdf',
    updatedAt: '20 Ott 2023',
  },
];

export const INITIAL_TASKS: Task[] = [
  {
    id: 'task-1',
    practiceId: 'prat-1',
    clientId: 'cli-1',
    propertyId: 'prop-1',
    title: 'Mario Rossi | Via Roma 18 · Terrasini',
    subtitle: 'Incarico da firmare',
    time: 'Entro 12:00',
    urgency: 'Priorità Alta',
    priority: 'high',
    status: 'pending',
    actionType: 'COMPLETA',
    targetSection: 'incarico',
  },
  {
    id: 'task-2',
    practiceId: 'prat-2',
    clientId: 'cli-3',
    propertyId: 'prop-3',
    title: 'Laura Bianchi | Via Libertà 42 · Palermo',
    subtitle: 'Antiriciclaggio da continuare',
    time: 'Oggi',
    urgency: 'In attesa documenti',
    priority: 'normal',
    status: 'pending',
    actionType: 'CONTINUA',
    targetSection: 'aml',
  },
  {
    id: 'task-3',
    practiceId: 'prat-1',
    clientId: 'cli-1',
    propertyId: 'prop-1',
    title: 'Carica Planimetria Catastale per Mario Rossi',
    subtitle: 'Necessaria per completamento fascicolo',
    time: 'Entro oggi',
    priority: 'high',
    status: 'pending',
    actionType: 'CARICA',
    targetSection: 'documenti',
  },
  {
    id: 'task-4',
    practiceId: 'prat-3',
    clientId: 'cli-6',
    propertyId: 'prop-4',
    title: 'Definisci compenso e durata incarico',
    subtitle: 'Monreale · Villa Singola',
    time: 'Entro venerdì',
    priority: 'normal',
    status: 'pending',
    actionType: 'DETTAGLI',
    targetSection: 'incarico',
  },
];

export const INITIAL_APPOINTMENTS: Appointment[] = [
  {
    id: 'app-1',
    time: '15:30',
    endTime: '16:30',
    title: 'Sopralluogo tecnico',
    type: 'Sopralluogo',
    propertyAddress: 'Via Roma 18',
    municipality: 'Terrasini',
    clientName: 'Mario Rossi',
    clientId: 'cli-1',
    practiceId: 'prat-1',
  },
  {
    id: 'app-2',
    time: '17:00',
    endTime: '18:00',
    title: 'Incontro Mandato Ready',
    type: 'Incontro Incarico',
    propertyAddress: 'Via Roma 12',
    municipality: 'Terrasini',
    clientName: 'Giuseppe Marino',
    clientId: 'cli-2',
  },
  {
    id: 'app-3',
    time: '14:30',
    endTime: '15:15',
    title: 'Visita Immobile',
    type: 'Visita Immobile',
    propertyAddress: 'Via Libertà 42',
    municipality: 'Palermo',
    clientName: 'Laura Bianchi',
    clientId: 'cli-3',
    practiceId: 'prat-2',
  },
];

export const INITIAL_WAITING_ITEMS: WaitingItem[] = [
  {
    id: 'wait-1',
    title: 'Firma digitale',
    codeOrLocation: '2023-4412',
    practiceId: 'prat-1',
    type: 'firma_digitale',
  },
  {
    id: 'wait-2',
    title: 'Visura ipotecaria',
    codeOrLocation: 'Via Libertà 42',
    practiceId: 'prat-2',
    type: 'visura',
  },
  {
    id: 'wait-3',
    title: 'Rilascio APE da geometra',
    codeOrLocation: 'Via dei Mulini 7',
    practiceId: 'prat-3',
    type: 'integrazione_documenti',
  },
];

export const INITIAL_DEADLINES: Deadline[] = [
  {
    id: 'dead-1',
    practiceId: 'prat-1',
    title: 'Incarico da completare e firmare',
    dueDate: 'Oggi, 12:00',
    group: 'oggi',
    completed: false,
    priority: 'high',
  },
  {
    id: 'dead-2',
    practiceId: 'prat-2',
    title: 'Integrazione Titolare Effettivo AML',
    dueDate: 'Domani, 18:00',
    group: 'questa_settimana',
    completed: false,
    priority: 'normal',
  },
  {
    id: 'dead-3',
    practiceId: 'prat-1',
    title: 'Recupero Atto di Provenienza originale',
    dueDate: '15 Ottobre 2023',
    group: 'in_ritardo',
    completed: false,
    priority: 'high',
  },
  {
    id: 'dead-4',
    practiceId: 'prat-1',
    title: 'Scadenza Mandato di Vendita',
    dueDate: '15 Maggio 2024',
    group: 'piu_avanti',
    completed: false,
    priority: 'normal',
  },
];
